export const countries = [
  { name: "Afganistán", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Alemania", code: "DE" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Antigua y Barbuda", code: "AG" },
  { name: "Arabia Saudita", code: "SA" },
  { name: "Argelia", code: "DZ" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaiyán", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bangladés", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Baréin", code: "BH" },
  { name: "Bélgica", code: "BE" },
  { name: "Belice", code: "BZ" },
  { name: "Benín", code: "BJ" },
  { name: "Bielorrusia", code: "BY" },
  { name: "Birmania (Myanmar)", code: "MM" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia y Herzegovina", code: "BA" },
  { name: "Botsuana", code: "BW" },
  { name: "Brasil", code: "BR" },
  { name: "Brunéi", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Bután", code: "BT" },
  { name: "Cabo Verde", code: "CV" },
  { name: "Camboya", code: "KH" },
  { name: "Camerún", code: "CM" },
  { name: "Canadá", code: "CA" },
  { name: "Catar", code: "QA" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  // ...continúa la lista según sea necesario
];
